import streamlit as st
st.title(" 💻Skills")
st.subheader(" Programming")
st.progress(80)
st.write("Python")
st.progress(90)
st.write("JavaScript")
st.progress(65)
st.write("PHP")
st.subheader(" Design")
st.progress(85)
st.write("Canva / UI Design")
st.subheader(" Tools")
st.write("- GitHub")
st.write("- VS Code")
st.write("- Streamlit")